# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "feature/github-workflow-create" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CAAS_CONFIG_PATH: ${{ github.workspace }}/coverage/certificate-key.caas

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Verify CaaS env variable
      run: echo $CAAS_CONFIG_PATH
    - name: Install CaaS maven Plugin
      run : mvn install:install-file -Dfile="./coverage/jacov-maven-plugin.jar" -DgroupId=com.qualityscroll.caas -DartifactId=jacov-maven-plugin -Dpackaging="jar" -Dversion="1.0.0-SNAPSHOT"
    - name: Run CaaS build
      run: mvn clean source:jar com.qualityscroll.caas:jacov-maven-plugin:1.0.0-SNAPSHOT:setup compile package -DskipTests
    - name: Run coverage built target
      run: java -jar -javaagent:coverage/java-runtime.jar target/helloworld-1.1.jar